-- ProjectOwner: CrewPortGlobal
-- Domain: crewport
-- BackwardCompatible: yes
-- RequiresDataBackfill: no
-- ExecutionPolicy: planning_only_do_not_apply_to_production_without_explicit_confirmation
-- Notes:
--   1. This file is a planning artifact only.
--   2. Do not apply to production on GTC1 without a separate approval step.
--   3. This schema must remain isolated from global auth tables and current Stripe workflow tables.
--   4. Core principle: GTC global identity != CrewPortGlobal operational profile.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS crewport;

CREATE TABLE IF NOT EXISTS crewport.physical_persons (
  person_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  crewport_user_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  gtc_user_id bigint NULL,
  primary_email text NOT NULL,
  secondary_email text NULL,
  full_name text NOT NULL,
  given_name text NULL,
  family_name text NULL,
  date_of_birth date NULL,
  nationality_code text NULL,
  phone_e164 text NULL,
  country_code text NULL,
  preferred_locale text NOT NULL DEFAULT 'en',
  lifecycle_state text NOT NULL DEFAULT 'draft' CHECK (lifecycle_state IN ('draft', 'active', 'suspended', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_crewport_physical_persons_email
  ON crewport.physical_persons (lower(primary_email));
CREATE INDEX IF NOT EXISTS idx_crewport_physical_persons_gtc_user
  ON crewport.physical_persons (gtc_user_id)
  WHERE gtc_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS crewport.seafarers (
  seafarer_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL UNIQUE REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  registration_state text NOT NULL DEFAULT 'draft' CHECK (registration_state IN ('draft', 'accepted', 'under_review', 'active', 'restricted', 'archived')),
  availability_state text NOT NULL DEFAULT 'unknown' CHECK (availability_state IN ('unknown', 'available', 'committed', 'inactive')),
  rank_code text NULL,
  department_code text NULL,
  years_experience numeric(6,2) NULL,
  current_location text NULL,
  summary text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crewport_seafarers_registration_state
  ON crewport.seafarers (registration_state);
CREATE INDEX IF NOT EXISTS idx_crewport_seafarers_rank_department
  ON crewport.seafarers (rank_code, department_code);

CREATE TABLE IF NOT EXISTS crewport.seafarer_documents (
  document_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seafarer_id uuid NOT NULL REFERENCES crewport.seafarers(seafarer_id) ON DELETE CASCADE,
  document_type text NOT NULL,
  document_number text NULL,
  issuing_country_code text NULL,
  issued_at date NULL,
  expires_at date NULL,
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'received', 'under_review', 'verified', 'rejected', 'expired')),
  file_storage_key text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crewport_seafarer_documents_owner
  ON crewport.seafarer_documents (seafarer_id, document_type);
CREATE INDEX IF NOT EXISTS idx_crewport_seafarer_documents_expiry
  ON crewport.seafarer_documents (expires_at);
CREATE INDEX IF NOT EXISTS idx_crewport_seafarer_documents_verification_state
  ON crewport.seafarer_documents (verification_state);

CREATE TABLE IF NOT EXISTS crewport.business_clients (
  business_client_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legal_name text NOT NULL,
  trading_name text NULL,
  registration_number text NULL,
  jurisdiction_code text NULL,
  country_code text NULL,
  website_url text NULL,
  operational_role text NOT NULL,
  onboarding_state text NOT NULL DEFAULT 'draft' CHECK (onboarding_state IN ('draft', 'invited', 'submitted', 'under_review', 'active', 'restricted', 'archived')),
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'under_review', 'verified', 'rejected', 'restricted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crewport_business_clients_state
  ON crewport.business_clients (onboarding_state, verification_state);
CREATE INDEX IF NOT EXISTS idx_crewport_business_clients_registration_number
  ON crewport.business_clients (registration_number);

CREATE TABLE IF NOT EXISTS crewport.company_representatives (
  representative_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_client_id uuid NOT NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  person_id uuid NOT NULL REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  role_title text NULL,
  authority_type text NOT NULL DEFAULT 'operator' CHECK (authority_type IN ('owner', 'director', 'authorized_signatory', 'operator', 'crewing_manager', 'observer')),
  invitation_state text NOT NULL DEFAULT 'draft' CHECK (invitation_state IN ('draft', 'invited', 'accepted', 'revoked')),
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'under_review', 'verified', 'rejected')),
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (business_client_id, person_id)
);

CREATE INDEX IF NOT EXISTS idx_crewport_company_representatives_business
  ON crewport.company_representatives (business_client_id, is_primary);

CREATE TABLE IF NOT EXISTS crewport.vessels (
  vessel_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_client_id uuid NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE SET NULL,
  vessel_name text NOT NULL,
  imo_number text NULL,
  vessel_type text NULL,
  flag_code text NULL,
  owner_name text NULL,
  manager_name text NULL,
  ownership_context text NULL,
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'under_review', 'verified', 'rejected', 'restricted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_crewport_vessels_imo_number
  ON crewport.vessels (imo_number)
  WHERE imo_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_crewport_vessels_business_client
  ON crewport.vessels (business_client_id);

CREATE TABLE IF NOT EXISTS crewport.crew_requests (
  crew_request_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_client_id uuid NOT NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE RESTRICT,
  requested_by_representative_id uuid NULL REFERENCES crewport.company_representatives(representative_id) ON DELETE SET NULL,
  vessel_id uuid NULL REFERENCES crewport.vessels(vessel_id) ON DELETE SET NULL,
  request_code text NOT NULL UNIQUE,
  title text NOT NULL,
  request_state text NOT NULL DEFAULT 'draft' CHECK (request_state IN ('draft', 'open', 'paused', 'under_review', 'fulfilled', 'cancelled', 'closed')),
  priority text NOT NULL DEFAULT 'standard' CHECK (priority IN ('low', 'standard', 'high', 'urgent')),
  needed_by_date date NULL,
  port_of_joining text NULL,
  notes text NULL,
  verification_gate text NOT NULL DEFAULT 'pending' CHECK (verification_gate IN ('pending', 'cleared', 'blocked')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crewport_crew_requests_state
  ON crewport.crew_requests (request_state, needed_by_date);
CREATE INDEX IF NOT EXISTS idx_crewport_crew_requests_business_client
  ON crewport.crew_requests (business_client_id, created_at DESC);

CREATE TABLE IF NOT EXISTS crewport.crew_request_positions (
  crew_request_position_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  crew_request_id uuid NOT NULL REFERENCES crewport.crew_requests(crew_request_id) ON DELETE CASCADE,
  rank_code text NOT NULL,
  department_code text NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  contract_duration_months integer NULL,
  wage_currency text NULL,
  wage_amount numeric(12,2) NULL,
  minimum_experience_months integer NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'shortlisting', 'offered', 'filled', 'cancelled')),
  requirement_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crewport_request_positions_request
  ON crewport.crew_request_positions (crew_request_id, status);
CREATE INDEX IF NOT EXISTS idx_crewport_request_positions_rank
  ON crewport.crew_request_positions (rank_code, department_code);

CREATE TABLE IF NOT EXISTS crewport.candidate_matches (
  candidate_match_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  crew_request_position_id uuid NOT NULL REFERENCES crewport.crew_request_positions(crew_request_position_id) ON DELETE CASCADE,
  seafarer_id uuid NOT NULL REFERENCES crewport.seafarers(seafarer_id) ON DELETE CASCADE,
  match_state text NOT NULL DEFAULT 'queued' CHECK (match_state IN ('queued', 'pending_review', 'shortlisted', 'presented', 'rejected', 'withdrawn', 'hired')),
  review_queue_state text NOT NULL DEFAULT 'pending' CHECK (review_queue_state IN ('pending', 'in_review', 'done', 'blocked')),
  score numeric(8,4) NULL,
  scoring_source text NULL,
  reviewer_gtc_user_id bigint NULL,
  review_notes text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz NULL,
  UNIQUE (crew_request_position_id, seafarer_id)
);

CREATE INDEX IF NOT EXISTS idx_crewport_candidate_matches_queue
  ON crewport.candidate_matches (review_queue_state, created_at);
CREATE INDEX IF NOT EXISTS idx_crewport_candidate_matches_state
  ON crewport.candidate_matches (match_state, score DESC NULLS LAST);

CREATE TABLE IF NOT EXISTS crewport.verification_events (
  verification_event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject_type text NOT NULL CHECK (subject_type IN ('physical_person', 'seafarer', 'document', 'business_client', 'representative', 'vessel', 'crew_request', 'candidate_match', 'billing_account', 'complaint', 'consent')),
  subject_id uuid NOT NULL,
  event_type text NOT NULL,
  outcome text NOT NULL CHECK (outcome IN ('pending', 'passed', 'failed', 'blocked', 'waived', 'info')),
  actor_type text NOT NULL DEFAULT 'system' CHECK (actor_type IN ('system', 'crewport_user', 'gtc_operator', 'business_representative', 'seafarer')),
  actor_gtc_user_id bigint NULL,
  actor_crewport_user_id bigint NULL,
  notes text NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crewport_verification_events_subject
  ON crewport.verification_events (subject_type, subject_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_crewport_verification_events_outcome
  ON crewport.verification_events (outcome, occurred_at DESC);

CREATE TABLE IF NOT EXISTS crewport.consent_records (
  consent_record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NULL REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  business_client_id uuid NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  consent_type text NOT NULL,
  consent_version text NOT NULL,
  consent_scope text NOT NULL CHECK (consent_scope IN ('public_onboarding', 'privacy', 'matching', 'verification', 'billing', 'complaints')),
  accepted_at timestamptz NOT NULL DEFAULT now(),
  evidence_source text NOT NULL DEFAULT 'web' CHECK (evidence_source IN ('web', 'api', 'admin', 'import')),
  evidence_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (
    (person_id IS NOT NULL AND business_client_id IS NULL)
    OR (person_id IS NULL AND business_client_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_crewport_consent_records_person
  ON crewport.consent_records (person_id, consent_type, accepted_at DESC)
  WHERE person_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_crewport_consent_records_business
  ON crewport.consent_records (business_client_id, consent_type, accepted_at DESC)
  WHERE business_client_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS crewport.billing_accounts (
  billing_account_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_scope text NOT NULL CHECK (account_scope IN ('person', 'business_client')),
  person_id uuid NULL REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  business_client_id uuid NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  account_status text NOT NULL DEFAULT 'draft' CHECK (account_status IN ('draft', 'active', 'suspended', 'closed')),
  billing_email text NULL,
  invoice_currency text NOT NULL DEFAULT 'USD',
  external_processor text NULL,
  external_customer_ref text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (account_scope = 'person' AND person_id IS NOT NULL AND business_client_id IS NULL)
    OR (account_scope = 'business_client' AND person_id IS NULL AND business_client_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_crewport_billing_accounts_scope
  ON crewport.billing_accounts (account_scope, account_status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_crewport_billing_accounts_person
  ON crewport.billing_accounts (person_id)
  WHERE person_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_crewport_billing_accounts_business
  ON crewport.billing_accounts (business_client_id)
  WHERE business_client_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS crewport.service_entitlements (
  entitlement_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  billing_account_id uuid NOT NULL REFERENCES crewport.billing_accounts(billing_account_id) ON DELETE CASCADE,
  entitlement_code text NOT NULL,
  subject_type text NOT NULL CHECK (subject_type IN ('person', 'business_client', 'crew_request', 'candidate_match', 'platform')),
  subject_id uuid NULL,
  entitlement_status text NOT NULL DEFAULT 'pending' CHECK (entitlement_status IN ('pending', 'active', 'suspended', 'expired', 'cancelled')),
  starts_at timestamptz NULL,
  ends_at timestamptz NULL,
  source_ref text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_crewport_service_entitlements_status
  ON crewport.service_entitlements (entitlement_status, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_crewport_service_entitlements_billing_account
  ON crewport.service_entitlements (billing_account_id, entitlement_code);

CREATE TABLE IF NOT EXISTS crewport.complaint_records (
  complaint_record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_code text NOT NULL UNIQUE,
  complaint_type text NOT NULL,
  complaint_status text NOT NULL DEFAULT 'open' CHECK (complaint_status IN ('open', 'under_review', 'resolved', 'dismissed', 'escalated', 'closed')),
  severity text NOT NULL DEFAULT 'standard' CHECK (severity IN ('low', 'standard', 'high', 'critical')),
  submitted_by_person_id uuid NULL REFERENCES crewport.physical_persons(person_id) ON DELETE SET NULL,
  submitted_by_business_client_id uuid NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE SET NULL,
  related_crew_request_id uuid NULL REFERENCES crewport.crew_requests(crew_request_id) ON DELETE SET NULL,
  related_candidate_match_id uuid NULL REFERENCES crewport.candidate_matches(candidate_match_id) ON DELETE SET NULL,
  summary text NOT NULL,
  details text NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz NULL,
  CHECK (
    submitted_by_person_id IS NOT NULL
    OR submitted_by_business_client_id IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_crewport_complaint_records_status
  ON crewport.complaint_records (complaint_status, severity, received_at DESC);

CREATE OR REPLACE VIEW crewport.seafarer_readiness AS
SELECT
  s.seafarer_id,
  p.person_id,
  p.crewport_user_id,
  p.gtc_user_id,
  p.full_name,
  p.primary_email,
  s.registration_state,
  s.availability_state,
  s.rank_code,
  s.department_code,
  COUNT(d.document_id) AS document_count,
  COUNT(*) FILTER (WHERE d.verification_state = 'verified') AS verified_document_count,
  COUNT(*) FILTER (WHERE d.verification_state IN ('pending', 'received', 'under_review')) AS pending_document_count,
  MIN(d.expires_at) FILTER (WHERE d.expires_at IS NOT NULL) AS earliest_document_expiry,
  CASE
    WHEN s.registration_state IN ('active', 'under_review')
      AND COUNT(d.document_id) > 0
      AND COUNT(*) FILTER (WHERE d.verification_state = 'verified') > 0
    THEN 'ready_for_matching_review'
    WHEN COUNT(d.document_id) = 0 THEN 'missing_documents'
    ELSE 'incomplete'
  END AS readiness_state
FROM crewport.seafarers s
JOIN crewport.physical_persons p ON p.person_id = s.person_id
LEFT JOIN crewport.seafarer_documents d ON d.seafarer_id = s.seafarer_id
GROUP BY s.seafarer_id, p.person_id, p.crewport_user_id, p.gtc_user_id, p.full_name, p.primary_email, s.registration_state, s.availability_state, s.rank_code, s.department_code;

CREATE OR REPLACE VIEW crewport.business_readiness AS
SELECT
  bc.business_client_id,
  bc.legal_name,
  bc.trading_name,
  bc.registration_number,
  bc.operational_role,
  bc.onboarding_state,
  bc.verification_state,
  COUNT(DISTINCT cr.representative_id) AS representative_count,
  COUNT(DISTINCT cr.representative_id) FILTER (WHERE cr.verification_state = 'verified') AS verified_representative_count,
  COUNT(DISTINCT v.vessel_id) AS vessel_count,
  COUNT(DISTINCT v.vessel_id) FILTER (WHERE v.verification_state = 'verified') AS verified_vessel_count,
  CASE
    WHEN bc.verification_state = 'verified'
      AND COUNT(DISTINCT cr.representative_id) FILTER (WHERE cr.verification_state = 'verified') > 0
    THEN 'ready_for_requests'
    WHEN bc.onboarding_state = 'draft' THEN 'draft'
    ELSE 'incomplete'
  END AS readiness_state
FROM crewport.business_clients bc
LEFT JOIN crewport.company_representatives cr ON cr.business_client_id = bc.business_client_id
LEFT JOIN crewport.vessels v ON v.business_client_id = bc.business_client_id
GROUP BY bc.business_client_id, bc.legal_name, bc.trading_name, bc.registration_number, bc.operational_role, bc.onboarding_state, bc.verification_state;

CREATE OR REPLACE VIEW crewport.open_crew_requests AS
SELECT
  r.crew_request_id,
  r.request_code,
  r.title,
  r.request_state,
  r.priority,
  r.needed_by_date,
  r.port_of_joining,
  bc.business_client_id,
  bc.legal_name AS business_client_name,
  v.vessel_name,
  rp.crew_request_position_id,
  rp.rank_code,
  rp.department_code,
  rp.quantity,
  rp.status AS position_status
FROM crewport.crew_requests r
JOIN crewport.business_clients bc ON bc.business_client_id = r.business_client_id
LEFT JOIN crewport.vessels v ON v.vessel_id = r.vessel_id
LEFT JOIN crewport.crew_request_positions rp ON rp.crew_request_id = r.crew_request_id
WHERE r.request_state IN ('open', 'under_review')
  AND rp.status IN ('open', 'shortlisting');

CREATE OR REPLACE VIEW crewport.match_review_queue AS
SELECT
  cm.candidate_match_id,
  cm.review_queue_state,
  cm.match_state,
  cm.score,
  cm.created_at,
  rp.crew_request_position_id,
  rp.rank_code,
  rp.department_code,
  r.crew_request_id,
  r.request_code,
  bc.legal_name AS business_client_name,
  s.seafarer_id,
  p.crewport_user_id,
  p.full_name,
  sr.readiness_state AS seafarer_readiness_state
FROM crewport.candidate_matches cm
JOIN crewport.crew_request_positions rp ON rp.crew_request_position_id = cm.crew_request_position_id
JOIN crewport.crew_requests r ON r.crew_request_id = rp.crew_request_id
JOIN crewport.business_clients bc ON bc.business_client_id = r.business_client_id
JOIN crewport.seafarers s ON s.seafarer_id = cm.seafarer_id
JOIN crewport.physical_persons p ON p.person_id = s.person_id
LEFT JOIN crewport.seafarer_readiness sr ON sr.seafarer_id = s.seafarer_id
WHERE cm.review_queue_state IN ('pending', 'in_review');

CREATE OR REPLACE VIEW crewport.project_entitlements AS
SELECT
  se.entitlement_id,
  se.entitlement_code,
  se.entitlement_status,
  se.starts_at,
  se.ends_at,
  ba.billing_account_id,
  ba.account_scope,
  ba.account_status,
  ba.invoice_currency,
  ba.external_processor,
  ba.external_customer_ref,
  pp.crewport_user_id,
  pp.gtc_user_id,
  bc.business_client_id,
  bc.legal_name AS business_client_name
FROM crewport.service_entitlements se
JOIN crewport.billing_accounts ba ON ba.billing_account_id = se.billing_account_id
LEFT JOIN crewport.physical_persons pp ON pp.person_id = ba.person_id
LEFT JOIN crewport.business_clients bc ON bc.business_client_id = ba.business_client_id;

COMMIT;
