-- ProjectOwner: CrewPortGlobal
-- PackageFile: 002_crewport_schema.sql
-- PackageRole: planning_only_schema
-- ExecutionPolicy: do_not_execute_without_explicit_manual_approval
-- Notes:
--   1. Planning artifact only.
--   2. Do not apply on production DB.
--   3. Do not apply on test DB.
--   4. Do not change global auth schema from this workstream.
--   5. Do not change current Stripe workflow from this workstream.
--   6. Reference artifact remains: db/migrations/20260510_crewport_initial_schema_v2_draft.sql.

BEGIN;

CREATE SCHEMA IF NOT EXISTS crewport;

CREATE OR REPLACE FUNCTION crewport.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS crewport.physical_persons (
  person_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  crewport_user_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  gtc_user_id bigint NULL,
  primary_email text NOT NULL,
  primary_email_verification_state text NOT NULL DEFAULT 'unverified' CHECK (primary_email_verification_state IN ('unverified', 'pending', 'verified', 'rejected')),
  primary_email_verified_at timestamptz NULL,
  secondary_email text NULL,
  full_name text NOT NULL,
  given_name text NULL,
  family_name text NULL,
  date_of_birth date NULL,
  nationality_code text NULL,
  residence_country_code text NULL,
  phone_e164 text NULL,
  country_code text NULL,
  preferred_locale text NOT NULL DEFAULT 'en',
  timezone_name text NULL,
  registration_source text NOT NULL DEFAULT 'crewport_public' CHECK (registration_source IN ('crewport_public', 'crewport_admin', 'business_invite', 'import', 'api')),
  onboarding_channel text NOT NULL DEFAULT 'web' CHECK (onboarding_channel IN ('web', 'admin', 'api', 'import')),
  lifecycle_state text NOT NULL DEFAULT 'draft' CHECK (lifecycle_state IN ('draft', 'active', 'suspended', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.user_roles (
  user_role_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  business_client_id uuid NULL,
  role_code text NOT NULL CHECK (role_code IN ('seafarer', 'business_representative', 'business_admin', 'verifier', 'reviewer', 'complaint_operator', 'billing_operator')),
  assignment_state text NOT NULL DEFAULT 'active' CHECK (assignment_state IN ('active', 'revoked')),
  granted_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.seafarers (
  seafarer_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NOT NULL UNIQUE REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  registration_state text NOT NULL DEFAULT 'draft' CHECK (registration_state IN ('draft', 'accepted', 'under_review', 'active', 'restricted', 'archived')),
  availability_state text NOT NULL DEFAULT 'unknown' CHECK (availability_state IN ('unknown', 'available', 'committed', 'inactive')),
  rank_code text NULL,
  department_code text NULL,
  years_experience numeric(6,2) NULL,
  current_location text NULL,
  summary text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.seafarer_documents (
  document_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seafarer_id uuid NOT NULL REFERENCES crewport.seafarers(seafarer_id) ON DELETE CASCADE,
  document_type text NOT NULL,
  document_number text NULL,
  issuing_country_code text NULL,
  issued_at date NULL,
  expires_at date NULL,
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'received', 'under_review', 'verified', 'rejected', 'expired')),
  file_storage_key text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.business_clients (
  business_client_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  legal_name text NOT NULL,
  trading_name text NULL,
  registration_number text NULL,
  jurisdiction_code text NULL,
  country_code text NULL,
  company_type text NULL,
  website_url text NULL,
  primary_business_email text NULL,
  primary_phone_e164 text NULL,
  registered_address_line_1 text NULL,
  registered_address_line_2 text NULL,
  registered_city text NULL,
  registered_postal_code text NULL,
  registered_country_code text NULL,
  operating_address_line_1 text NULL,
  operating_address_line_2 text NULL,
  operating_city text NULL,
  operating_postal_code text NULL,
  operating_country_code text NULL,
  operational_role text NOT NULL,
  onboarding_state text NOT NULL DEFAULT 'draft' CHECK (onboarding_state IN ('draft', 'invited', 'submitted', 'under_review', 'active', 'restricted', 'archived')),
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'under_review', 'verified', 'rejected', 'restricted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.company_representatives (
  representative_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_client_id uuid NOT NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  person_id uuid NOT NULL REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  role_title text NULL,
  authority_type text NOT NULL DEFAULT 'operator' CHECK (authority_type IN ('owner', 'director', 'authorized_signatory', 'operator', 'crewing_manager', 'observer')),
  invitation_state text NOT NULL DEFAULT 'draft' CHECK (invitation_state IN ('draft', 'invited', 'accepted', 'revoked')),
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'under_review', 'verified', 'rejected')),
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (business_client_id, person_id)
);

ALTER TABLE crewport.user_roles
  ADD CONSTRAINT fk_crewport_user_roles_business_client
  FOREIGN KEY (business_client_id) REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS crewport.representative_documents (
  representative_document_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  representative_id uuid NOT NULL REFERENCES crewport.company_representatives(representative_id) ON DELETE CASCADE,
  document_type text NOT NULL,
  document_number text NULL,
  issued_at date NULL,
  expires_at date NULL,
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'received', 'under_review', 'verified', 'rejected', 'expired')),
  file_storage_key text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.business_documents (
  business_document_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_client_id uuid NOT NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  document_type text NOT NULL,
  document_number text NULL,
  issued_by text NULL,
  issued_at date NULL,
  expires_at date NULL,
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'received', 'under_review', 'verified', 'rejected', 'expired')),
  file_storage_key text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.vessels (
  vessel_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_name text NOT NULL,
  imo_number text NULL,
  call_sign text NULL,
  mmsi text NULL,
  vessel_type text NULL,
  flag_code text NULL,
  port_of_registry text NULL,
  registry_country_code text NULL,
  owner_name text NULL,
  manager_name text NULL,
  ownership_context text NULL,
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'under_review', 'verified', 'rejected', 'restricted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.business_client_vessels (
  business_client_vessel_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_client_id uuid NOT NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  vessel_id uuid NOT NULL REFERENCES crewport.vessels(vessel_id) ON DELETE CASCADE,
  relationship_type text NOT NULL CHECK (relationship_type IN ('owner', 'manager', 'operator', 'crewing_agent', 'charterer', 'other')),
  relationship_state text NOT NULL DEFAULT 'active' CHECK (relationship_state IN ('active', 'inactive', 'revoked', 'historical')),
  is_primary boolean NOT NULL DEFAULT false,
  effective_from date NULL,
  effective_to date NULL,
  notes text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (business_client_id, vessel_id, relationship_type)
);

CREATE TABLE IF NOT EXISTS crewport.vessel_documents (
  vessel_document_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vessel_id uuid NOT NULL REFERENCES crewport.vessels(vessel_id) ON DELETE CASCADE,
  document_type text NOT NULL,
  document_number text NULL,
  issued_by text NULL,
  issued_at date NULL,
  expires_at date NULL,
  verification_state text NOT NULL DEFAULT 'pending' CHECK (verification_state IN ('pending', 'received', 'under_review', 'verified', 'rejected', 'expired')),
  file_storage_key text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.crew_requests (
  crew_request_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_client_id uuid NOT NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE RESTRICT,
  requested_by_representative_id uuid NULL REFERENCES crewport.company_representatives(representative_id) ON DELETE SET NULL,
  vessel_id uuid NULL REFERENCES crewport.vessels(vessel_id) ON DELETE SET NULL,
  request_code text NOT NULL UNIQUE,
  title text NOT NULL,
  request_state text NOT NULL DEFAULT 'draft' CHECK (request_state IN ('draft', 'open', 'paused', 'under_review', 'fulfilled', 'cancelled', 'closed')),
  priority text NOT NULL DEFAULT 'standard' CHECK (priority IN ('low', 'standard', 'high', 'urgent')),
  needed_by_date date NULL,
  embarkation_window_start date NULL,
  embarkation_window_end date NULL,
  port_of_joining text NULL,
  notes text NULL,
  verification_gate text NOT NULL DEFAULT 'pending' CHECK (verification_gate IN ('pending', 'cleared', 'blocked')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.crew_request_positions (
  crew_request_position_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  crew_request_id uuid NOT NULL REFERENCES crewport.crew_requests(crew_request_id) ON DELETE CASCADE,
  rank_code text NOT NULL,
  department_code text NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  contract_duration_months integer NULL,
  wage_currency text NULL,
  wage_amount numeric(12,2) NULL,
  minimum_experience_months integer NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'shortlisting', 'offered', 'filled', 'cancelled')),
  requirement_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.candidate_matches (
  candidate_match_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  crew_request_position_id uuid NOT NULL REFERENCES crewport.crew_request_positions(crew_request_position_id) ON DELETE CASCADE,
  seafarer_id uuid NOT NULL REFERENCES crewport.seafarers(seafarer_id) ON DELETE CASCADE,
  attempt_no integer NOT NULL CHECK (attempt_no > 0),
  is_current_attempt boolean NOT NULL DEFAULT true,
  supersedes_candidate_match_id uuid NULL REFERENCES crewport.candidate_matches(candidate_match_id) ON DELETE SET NULL,
  match_state text NOT NULL DEFAULT 'queued' CHECK (match_state IN ('queued', 'pending_review', 'shortlisted', 'presented', 'rejected', 'withdrawn', 'hired')),
  review_queue_state text NOT NULL DEFAULT 'pending' CHECK (review_queue_state IN ('pending', 'in_review', 'done', 'blocked')),
  score numeric(8,4) NULL,
  scoring_source text NULL,
  reviewer_gtc_user_id bigint NULL,
  reviewer_crewport_user_id bigint NULL,
  review_notes text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz NULL,
  closed_at timestamptz NULL,
  UNIQUE (crew_request_position_id, seafarer_id, attempt_no)
);

CREATE TABLE IF NOT EXISTS crewport.verification_events (
  verification_event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject_type text NOT NULL CHECK (subject_type IN ('physical_person', 'seafarer', 'document', 'business_client', 'business_document', 'representative', 'representative_document', 'vessel', 'vessel_document', 'business_vessel_relationship', 'crew_request', 'candidate_match', 'billing_account', 'complaint', 'consent', 'user_role')),
  subject_id uuid NOT NULL,
  event_type text NOT NULL,
  outcome text NOT NULL CHECK (outcome IN ('pending', 'passed', 'failed', 'blocked', 'waived', 'info')),
  actor_type text NOT NULL DEFAULT 'system' CHECK (actor_type IN ('system', 'crewport_user', 'gtc_operator', 'business_representative', 'seafarer')),
  actor_gtc_user_id bigint NULL,
  actor_crewport_user_id bigint NULL,
  notes text NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.consent_records (
  consent_record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id uuid NULL REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  business_client_id uuid NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  consent_type text NOT NULL,
  consent_version text NOT NULL,
  consent_scope text NOT NULL CHECK (consent_scope IN ('public_onboarding', 'privacy', 'matching', 'verification', 'billing', 'complaints')),
  accepted_at timestamptz NOT NULL DEFAULT now(),
  evidence_source text NOT NULL DEFAULT 'web' CHECK (evidence_source IN ('web', 'api', 'admin', 'import')),
  evidence_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  CHECK (
    (person_id IS NOT NULL AND business_client_id IS NULL)
    OR (person_id IS NULL AND business_client_id IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS crewport.billing_accounts (
  billing_account_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_scope text NOT NULL CHECK (account_scope IN ('person', 'business_client')),
  person_id uuid NULL REFERENCES crewport.physical_persons(person_id) ON DELETE CASCADE,
  business_client_id uuid NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE CASCADE,
  account_status text NOT NULL DEFAULT 'draft' CHECK (account_status IN ('draft', 'active', 'suspended', 'closed')),
  billing_email text NULL,
  invoice_currency text NOT NULL DEFAULT 'USD',
  external_processor text NULL,
  external_customer_ref text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (account_scope = 'person' AND person_id IS NOT NULL AND business_client_id IS NULL)
    OR (account_scope = 'business_client' AND person_id IS NULL AND business_client_id IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS crewport.service_entitlements (
  entitlement_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  billing_account_id uuid NOT NULL REFERENCES crewport.billing_accounts(billing_account_id) ON DELETE CASCADE,
  entitlement_code text NOT NULL,
  subject_type text NOT NULL CHECK (subject_type IN ('person', 'business_client', 'crew_request', 'candidate_match', 'platform')),
  subject_id uuid NULL,
  entitlement_status text NOT NULL DEFAULT 'pending' CHECK (entitlement_status IN ('pending', 'active', 'suspended', 'expired', 'cancelled')),
  starts_at timestamptz NULL,
  ends_at timestamptz NULL,
  source_ref text NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crewport.complaint_records (
  complaint_record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_code text NOT NULL UNIQUE,
  complaint_type text NOT NULL,
  complaint_status text NOT NULL DEFAULT 'open' CHECK (complaint_status IN ('open', 'under_review', 'resolved', 'dismissed', 'escalated', 'closed')),
  severity text NOT NULL DEFAULT 'standard' CHECK (severity IN ('low', 'standard', 'high', 'critical')),
  submitted_by_person_id uuid NULL REFERENCES crewport.physical_persons(person_id) ON DELETE SET NULL,
  submitted_by_business_client_id uuid NULL REFERENCES crewport.business_clients(business_client_id) ON DELETE SET NULL,
  related_crew_request_id uuid NULL REFERENCES crewport.crew_requests(crew_request_id) ON DELETE SET NULL,
  related_candidate_match_id uuid NULL REFERENCES crewport.candidate_matches(candidate_match_id) ON DELETE SET NULL,
  summary text NOT NULL,
  details text NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    submitted_by_person_id IS NOT NULL
    OR submitted_by_business_client_id IS NOT NULL
  )
);

CREATE TRIGGER trg_crewport_physical_persons_updated_at
BEFORE UPDATE ON crewport.physical_persons
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_user_roles_updated_at
BEFORE UPDATE ON crewport.user_roles
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_seafarers_updated_at
BEFORE UPDATE ON crewport.seafarers
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_seafarer_documents_updated_at
BEFORE UPDATE ON crewport.seafarer_documents
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_business_clients_updated_at
BEFORE UPDATE ON crewport.business_clients
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_company_representatives_updated_at
BEFORE UPDATE ON crewport.company_representatives
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_representative_documents_updated_at
BEFORE UPDATE ON crewport.representative_documents
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_business_documents_updated_at
BEFORE UPDATE ON crewport.business_documents
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_vessels_updated_at
BEFORE UPDATE ON crewport.vessels
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_business_client_vessels_updated_at
BEFORE UPDATE ON crewport.business_client_vessels
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_vessel_documents_updated_at
BEFORE UPDATE ON crewport.vessel_documents
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_crew_requests_updated_at
BEFORE UPDATE ON crewport.crew_requests
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_crew_request_positions_updated_at
BEFORE UPDATE ON crewport.crew_request_positions
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_candidate_matches_updated_at
BEFORE UPDATE ON crewport.candidate_matches
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_billing_accounts_updated_at
BEFORE UPDATE ON crewport.billing_accounts
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_service_entitlements_updated_at
BEFORE UPDATE ON crewport.service_entitlements
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

CREATE TRIGGER trg_crewport_complaint_records_updated_at
BEFORE UPDATE ON crewport.complaint_records
FOR EACH ROW EXECUTE FUNCTION crewport.set_updated_at();

COMMIT;